version: 2.1

jobs:
  build:
    docker:
      - image: python:3.10
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Run tests in Coursework
          command: python FinalProject/Tests/StatsFunctionTest/test_stats_funcitons.py

workflows:
  build:
    jobs:
      - build
