version: 2.1

jobs:
  build:
    docker:
      - image: python:3.10
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Run tests in CircleCi test folder
          command: python CircleCI_test/TestFolder/test
      # - run:
      #     name: Run tests in Coursework
      #     command: python Coursework/

workflows:
  build: 
    jobs:
      - build
