version: 2.1

jobs:
  build:
    docker:
      - image: python 3.10
    steps:
      - checkout: main
      - run:
        name: Install dependencies
        command: pip install -r requirements.txt
      -run:
        name: Run tests
        command: python test.py
      

workflows:
  verision: 2
  build: 
  jobs:
    - build