version: 2.1

jobs:
  build:
    docker:
      - image: python:3.10
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Run tests for PMCC
          command: python FinalProject/Tests/StatsFunctionsTest/test_pmcc.py
      - run:
          name: Run tests for Linear Regression
          command: python FinalProject/Tests/StatsFunctionsTest/test_linear_regression.py
      - run:
          name: Run tests for Dictionary Filtering
          command: python FinalProject/Tests/StatsFunctionsTest/test_filter_dict.py
      - run:
          name: Run tests for Mean
          command: python FinalProject/Tests/StatsFunctionsTest/test_mean.py
      - run:
          name: Run tests for Complex Functions
          command: python FinalProject/Tests/StatsFunctionsTest/test_ComplexFunctions.py

workflows:
  build:
    jobs:
      - build
