version: 2.1

jobs:
  build:
    docker:
      - image: python:3.10
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Run tests for basic functions
          command: python FinalProject/Tests/StatsFunctionsTest/test_BasicFunctions.py
      - run:
          name: Run tests for complex functions
          command: python FinalProject/Tests/StatsFunctionsTest/test_ComplexFunctions.py

workflows:
  build:
    jobs:
      - build
